-- CreateEnum
CREATE TYPE "ProgressStatus" AS ENUM ('LOCKED', 'UNSTARTEDREQUIRED', 'STARTEDREQUIRED', 'UNSTARTEDOPTIONAL', 'STARTEDOPTIONAL', 'COMPLETE');

-- AlterTable
ALTER TABLE "SitePage" ADD COLUMN     "progress" "ProgressStatus" NOT NULL DEFAULT 'UNSTARTEDREQUIRED';
